import json
import uuid
import operator
from typing import TypedDict, List, Dict, Annotated, Any
from dotenv import load_dotenv
from langgraph.graph import StateGraph, END
# from langchain_ollama import ChatOllama
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import os
from datetime import datetime, timezone


# ---------------- STATE ----------------
class AgentState(TypedDict, total=False):
    text: str
    id_registry: Dict[str, Any]
    final_resources: Annotated[List[dict], operator.add]
    rulebook_paths: Dict[str, str]
    model: str          # frontend model selector value, propagated through the graph

# ---------------- LLM ----------------
# llm = ChatOllama(model="qwen2.5:latest", temperature=0)
# llm = ChatOllama(model="deepseek-coder-v2", temperature=0)

# Dependency graph - what each resource needs
RESOURCE_DEPENDENCIES = {
    "Patient": [],
    "Organization": [],
    "Practitioner": ["Patient"],
    "PractitionerRole": ["Patient", "Practitioner", "Organization"],
    "Encounter": ["Patient", "Practitioner", "PractitionerRole", "Organization"],
    "Observation": ["Patient", "Encounter"],
    "ObservationVitalSigns": ["Patient", "Encounter"],
    "ObservationBodyMeasurement": ["Patient", "Encounter"],
    "Condition": ["Patient", "Encounter"],
    "Procedure": ["Patient", "Encounter", "Practitioner"],
    "DiagnosticReportLab": ["Patient", "Practitioner", "Observation"],
    "DiagnosticReportImaging": ["Patient", "Practitioner", "Observation"],
    "MedicationRequest": ["Patient", "Practitioner"],
    "MedicationStatement": ["Patient"],
    "Medication": ["Patient"],
    "AllergyIntolerance": ["Patient"],
    "DocumentReference": ["Patient"],
    "DischargeSummaryRecord": ["Patient", "Encounter"],  # Composition
    "DiagnosticReportRecord": ["Patient", "DiagnosticReportLab"]  # Composition
}

abdm_extraction_dictionary = {
    "ClinicalArtifacts": {
        "DischargeSummaryRecord": "A Clinical document used to represent the discharge summary record for ABDM HDE data set. It provides a single coherent clinical statement with clinical attestation of a patient's stay.",
        "DiagnosticReportRecord": "A Clinical Artifact representing diagnostic reports, including Radiology and Laboratory reports, that can be shared across the health ecosystem. It provides a single coherent statement of meaning with clinical attestation.",
    },
    "OtherResources": {
        "Patient": "This profile sets minimum expectations for the Patient resource to record, search, and fetch basic demographics and other administrative information about an individual patient.",
        "Practitioner": "This profile sets minimum expectations for the Practitioner resource to record, search, and fetch basic demographics and other administrative information about an individual practitioner.",
        "PractitionerRole": "This profile sets minimum expectations for the PractitionerRole resource to record, search, and fetch the practitioner role for a practitioner within an organization.",
        "Organization": "This profile sets minimum expectations for the Organization resource to record, search, and fetch information about a healthcare organization.",
        "Encounter": "This profile sets minimum expectations for the Encounter resource to record, search, and fetch basic encounter information for an individual patient, such as inpatient or outpatient status.",
        "Condition": "This profile sets minimum expectations for the Condition resource to record, search, and fetch a list of conditions, problems, or diagnoses associated with a patient.",
        "Procedure": "This profile sets minimum expectations for the Procedure resource to record, search, and fetch details of clinical actions or procedures performed on or with a patient.",
        "Observation": "Represents an individual laboratory test and result value, or a finding. It sets minimum expectations for the Observation resource to record, search, and fetch clinical observations associated with a patient.",
        "DiagnosticReportLab": "This profile represents the set of information related to the Laboratory diagnosis report generated by laboratory services like CBC, Lipid Panel, Urinalysis, etc.",
        "DiagnosticReportImaging": "This profile represents the set of information related to the Imaging diagnosis report generated by imaging services like Radiology, Cardiology, or Endoscopy.",
        "ObservationVitalSigns": "This profile sets minimum expectations for the Observation resource to record, search, and fetch vital signs like Blood Pressure, Heart Rate, and Temperature.",
        "ObservationBodyMeasurement": "This profile sets minimum expectations for the Observation resource to record, search, and fetch physical metrics such as Body Weight, Height, and BMI.",
        "ObservationGeneralAssessment": "This profile sets minimum expectations for the ObservationGeneralAssessment to record, search, and fetch the details of the general health assessment or qualitative scores of a patient.",
        "ObservationLifestyle": "This profile sets minimum expectations for the ObservationLifestyle to record, search, and fetch details of the lifestyle of the patient (e.g., smoking or alcohol status).",
        "ObservationPhysicalActivity": "This profile sets minimum expectations for the ObservationPhysicalActivity to record, search, and fetch details of the physical movement and exercise levels of the patient.",
        "ObservationWomenHealth": "This profile sets minimum expectations for the Observation resource to record specific metrics related to obstetric and gynecological history, such as LMP and pregnancy status.",
        "MedicationRequest": "This resource is used to record a patient's medication prescription or order. It sets minimum expectations to record, search, and fetch medications associated with a patient.",
        "MedicationStatement": "Used to record a patient's medication information, specifically medications consumed by the patient in the past, present, or future.",
        "Medication": "This profile sets the minimum expectations for the medication resource in order to store various details about a given medicine (ingredients, form, etc.).",
        "AllergyIntolerance": "Records the risk of harmful or undesirable physiological response unique to an individual associated with exposure to a substance (food, drug, or material).",
        "FamilyMemberHistory": "This profile sets minimum expectations to record, search, and fetch significant health conditions of the patient's relatives for risk assessment.",
        "Immunization": "This profile sets minimum expectations for the Immunization resource to record, fetch, and search immunization history and vaccine administration associated with a patient.",
        "CarePlan": "This profile sets minimum expectations for the CarePlan resource to record, search, and fetch assessment and plan of treatment data associated with a patient.",
        "ServiceRequest": "A record of a request for service such as diagnostic investigations, treatments, or referrals to be performed.",
        "Specimen": "This profile sets minimum expectations for the Specimen resource to record details about a biological sample (blood, urine, etc.) used in diagnostic testing.",
        "ImagingStudy": "Representation of the content produced in a DICOM imaging study, comprising a set of series and instances (images) acquired in a common context.",
        "DocumentReference": "This profile sets minimum expectations for searching and fetching patient documents, including clinical notes, using a reference to a document.",
        "Binary": "This profile sets minimum expectations for the Binary resource to search and fetch the data of a single raw artifact (e.g., PDF or scanned image) in its native format.",
        "Media": "This profile sets minimum expectations for the Media resource to search and fetch media like a photo, video, or audio recording acquired or used in healthcare."
    }
}


# Load .env for local development (Docker injects vars via env_file)
_here = os.path.dirname(__file__)
for _candidate in [
    os.path.join(_here, "../../.env"),
    os.path.join(_here, "../.env"),
    "/.env",
    "/app/.env",
]:
    if os.path.isfile(_candidate):
        load_dotenv(dotenv_path=_candidate)
        break
else:
    load_dotenv()

_PROJECT_ID = os.getenv("PROJECT_ID", "bcd-prototypes")
_REGION     = os.getenv("REGION", "global")
_ENDPOINT   = os.getenv("ENDPOINT", "aiplatform.googleapis.com")

# ── Authentication ────────────────────────────────────────────────────────────
# Priority 1: Google Application Default Credentials (ADC)
#   - Works automatically on GCP VMs via metadata server
#   - Run 'gcloud auth application-default login' for local dev
# Priority 2: API_KEY from .env (for local/testing)

_cached_credentials = None

# ── LLM client cache (thread-safe, 55-min TTL) ───────────────────────────────
import threading as _threading
import time as _time
_llm_cache: dict = {}
_llm_cache_ts: dict = {}
_llm_cache_lock = _threading.Lock()
_LLM_CACHE_TTL = 3300  # 55 minutes — OAuth2 tokens expire after 60 min

# ── Per-resource token limits — smaller resources get smaller budgets ─────────
# Capped output shrinks streaming time by 20-40% for simple resources.
_RESOURCE_TOKEN_LIMITS: dict = {
    "Patient": 2048, "Practitioner": 2048, "PractitionerRole": 1024,
    "Organization": 2048, "Appointment": 1024, "Specimen": 1024,
    "Encounter": 2048, "AllergyIntolerance": 1024, "Immunization": 1024,
    "FamilyMemberHistory": 1024, "MedicationRequest": 2048,
    "MedicationStatement": 2048, "Medication": 1024, "ServiceRequest": 1024,
    "Condition": 4096, "Procedure": 4096, "Observation": 4096,
    "DiagnosticReportLab": 4096, "DiagnosticReport": 4096, "ImagingStudy": 2048,
    "CarePlan": 4096, "Media": 1024,
    "DocumentReference": 4096, "Binary": 1024,
    "Composition": 8192, "Bundle": 8192,
    "InsurancePlan": 8192, "InsurancePlanBundle": 8192,
    "Coverage": 4096, "Claim": 4096, "ClaimResponse": 4096,
    "Task": 2048, "Communication": 1024, "CommunicationRequest": 1024,
    "PaymentNotice": 1024, "PaymentReconciliation": 2048,
}

def _get_vertex_token() -> str:
    """Return a fresh OAuth2 access token via ADC, or fall back to API_KEY."""
    global _cached_credentials
    try:
        import google.auth
        import google.auth.transport.requests
        if _cached_credentials is None:
            _cached_credentials, _ = google.auth.default(
                scopes=["https://www.googleapis.com/auth/cloud-platform"]
            )
        _cached_credentials.refresh(google.auth.transport.requests.Request())
        return _cached_credentials.token
    except Exception as e:
        fallback = os.getenv("API_KEY", "")
        print(f"⚠️  ADC unavailable ({e}), falling back to API_KEY env var")
        return fallback

# ── Model ──────────────────────────────────────────────────────────────────
MODEL_MAP = {
    "gemma4": "publishers/google/models/gemma-4-26b-a4b-it-maas",
}
_DEFAULT_MODEL = "gemma4"

def get_llm(model: str = _DEFAULT_MODEL, max_tokens: int = 4096):
    """
    Return a cached ChatGoogleGenerativeAI client.
    Clients are reused for up to 55 minutes to avoid per-call auth overhead.
    Temperature is 0.1 — deterministic enough for structured JSON extraction
    and noticeably faster than 0.7 (less sampling exploration).
    """
    cache_key = (model, max_tokens)
    now = _time.monotonic()
    with _llm_cache_lock:
        if cache_key in _llm_cache and now - _llm_cache_ts[cache_key] < _LLM_CACHE_TTL:
            return _llm_cache[cache_key]

    # Refresh credentials outside the lock (can be slow)
    _get_vertex_token()
    vertex_model = MODEL_MAP.get(model, MODEL_MAP[_DEFAULT_MODEL])

    from langchain_google_genai import ChatGoogleGenerativeAI
    llm = ChatGoogleGenerativeAI(
        model=vertex_model,
        project=_PROJECT_ID,
        location="global",
        temperature=0.3,
        max_output_tokens=max_tokens,
        credentials=_cached_credentials,
    )
    with _llm_cache_lock:
        _llm_cache[cache_key] = llm
        _llm_cache_ts[cache_key] = now
    return llm

def check_llm_health():
    """Verify that we can at least get a token or the API_KEY is set."""
    token = _get_vertex_token()
    if token and len(token) > 10:
        return True, "ok"
    return False, "auth_failed"


def get_must_resources(artifact):
    if artifact == "DiagnosticReportRecord":
        return [
            "DocumentBundle", "DiagnosticReportRecord", "Patient", "Practitioner", 
            "Organization", "DiagnosticReportLab", "Observation", "DocumentReference"
        ]
    elif artifact == "DischargeSummaryRecord":
        return [
            "DocumentBundle", "DischargeSummaryRecord", "Patient", "Encounter", "Practitioner", 
            "Organization", "Condition", "Procedure", "Specimen", "Appointment", 
            "Observation", "DocumentReference"
        ]
    return []

# ---------------- JSON EXTRACTION ----------------
def extract_json(text: str):
    if not text or not text.strip():
        return None
    
    # Remove markdown code blocks
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    if text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    text = text.strip()
    
    decoder = json.JSONDecoder()
    idx = 0
    
    while idx < len(text):
        try:
            obj, end = decoder.raw_decode(text[idx:])
            if isinstance(obj, str):
                try:
                    obj = json.loads(obj)
                except:
                    pass
            return obj
        except json.JSONDecodeError:
            idx += 1
    return None

# ---------------- NORMALIZE FUNCTIONS ----------------
def ensure_id(resource):
    if not isinstance(resource, dict):
        return resource
    if "id" not in resource or not resource["id"]:
        resource["id"] = str(uuid.uuid4())
    return resource

def normalize_resource_output(res, resource_type):
    """Convert any input to single dict or list of dicts."""
    if isinstance(res, str):
        parsed = extract_json(res)
        if parsed:
            res = parsed
    
    if isinstance(res, dict):
        return [res]
    elif isinstance(res, list):
        return res
    else:
        # Create minimal resource
        return [{
            "resourceType": resource_type,
            "id": str(uuid.uuid4()),
            "meta": {"profile": [f"https://nrces.in/ndhm/fhir/r4/StructureDefinition/{resource_type}"]}
        }]

def get_single_resource(resources_list, resource_type):
    """Get first valid resource from list."""
    for res in resources_list:
        if isinstance(res, dict) and res.get("resourceType") == resource_type:
            return res
    # Return first item or create new
    if resources_list:
        res = resources_list
        if isinstance(res, dict):
            res["resourceType"] = resource_type
            return res
    return {
        "resourceType": resource_type,
        "id": str(uuid.uuid4()),
        "meta": {"profile": [f"https://nrces.in/ndhm/fhir/r4/StructureDefinition/{resource_type}"]}
    }
# ---------------- CORE AGENT FUNCTION ----------------
def run_extraction_agent(state: AgentState, resource_type: str, model: str = _DEFAULT_MODEL):
    rulebook_path = state['rulebook_paths'].get(resource_type)
     # Load rulebook content
    rulebook_content = ""
    if rulebook_path and os.path.exists(rulebook_path):
        with open(rulebook_path, 'r', encoding='utf-8') as f:
            rulebook_content = f.read()
    
    prompt = f'''
    Extract ONLY a valid HL7 FHIR R4 {resource_type} resource (or array of resources) from the clinical text.

RULEBOOK (ADDITIONAL STRUCTURE GUIDANCE):
{rulebook_content}
    

CLINICAL TEXT:
{state["text"]}

STRICT REQUIREMENTS (NON-NEGOTIABLE):

• Output MUST be valid JSON only  
• Output MUST start with "{{" or "["  
• DO NOT output markdown, comments, explanations, or code fences  
• DO NOT hallucinate or infer missing data  
• Extract ONLY information explicitly present in the clinical text  
• Omit any field whose value is not clearly present  

FHIR + ABDM CONSTRAINTS:

• Conform to HL7 FHIR R4 structure  
• Conform to ABDM / NDHM profiling expectations  
• Include "resourceType" correctly  
• Every resource MUST contain an "id"  
• "id" MUST be a UUID string (RFC-4122 format)  
• Use only fields relevant to {resource_type}  
• DO NOT include empty objects or empty arrays  
• DO NOT include null values  

TERMINOLOGY RULES:

• Clinical concepts → SNOMED CT codes when applicable  
• Laboratory / measurements → LOINC codes when applicable  
• Units → UCUM codes  
• Include proper system URLs:

  SNOMED CT → http://snomed.info/sct  
  LOINC → http://loinc.org  
  UCUM → http://unitsofmeasure.org  

• If no explicit coded value exists in text → use only "text" representation  
• NEVER fabricate codes

REFERENCE & LINKING RULES:

• Use URN UUID references when linking resources:

  "reference": "urn:uuid:<resource-id>"

• Only create references that are explicitly justified by the text  
• DO NOT create imaginary relationships  

DATA ACCURACY RULES:

• Preserve original clinical meaning  
• Preserve numeric precision exactly  
• Preserve dates exactly as written  
• DO NOT normalize, reinterpret, or guess  

OUTPUT FORMAT:

Return ONLY the JSON resource(s) for {resource_type}.
'''

    try:
        _max_tok = _RESOURCE_TOKEN_LIMITS.get(resource_type, 4096)
        fresh_llm = get_llm(state.get('model', _DEFAULT_MODEL), max_tokens=_max_tok)
        response = fresh_llm.invoke([HumanMessage(content=prompt)])
        raw_output = response.content.strip()
        print(f"\n🔍 Raw output for {resource_type}:\n{raw_output[:500]}...")
        
        parsed = extract_json(raw_output)
        if parsed:
            return parsed
        
        print(f"⚠️ Could not parse JSON for {resource_type}")
        
    except Exception as e:
        print(f"❌ Error for {resource_type}: {e}")
    
    # Fallback minimal resource
    return [{
        "resourceType": resource_type,
        "id": str(uuid.uuid4()),
        "meta": {"profile": [f"https://nrces.in/ndhm/fhir/r4/StructureDefinition/{resource_type}"]}
    }]


_node_cache = {}

def create_resource_node(resource_type: str):
    """Factory function with caching - handles MULTIPLE observations + Composition"""
    if resource_type in _node_cache:
        return _node_cache[resource_type]
    
    def node(state: AgentState):
        # ✅ SPECIAL CASE: Clinical Artifacts use Composition structure
        model = state.get('model', _DEFAULT_MODEL)
        if resource_type in ["DiagnosticReportRecord", "DischargeSummaryRecord"]:
            actual_resource_type = "Composition"
            is_composition = True
        else:
            actual_resource_type = resource_type
            is_composition = False
        
        resources = run_extraction_agent(state, actual_resource_type, model)
        resources = normalize_resource_output(resources, actual_resource_type)
        
        # ✅ KEEP YOUR ORIGINAL MULTIPLE HANDLING LOGIC
        if isinstance(resources, list):
            safe_resources = []
            max_items = 1 if is_composition else 100  # ✅ Composition=1, Others=10
            for res in resources[:max_items]:
                if isinstance(res, dict):
                    if res.get("resourceType") != actual_resource_type:
                        res["resourceType"] = actual_resource_type
                    
                    # ✅ Composition profile forcing
                    if is_composition:
                        res.setdefault('meta', {})['profile'] = [
                            f"https://nrces.in/ndhm/fhir/r4/StructureDefinition/{resource_type}"
                        ]
                    
                    res = ensure_id(res)
                    
                    # Add patient reference (YOUR ORIGINAL LOGIC)
                    patient_id = state['id_registry'].get('patient_id')
                    if patient_id and 'subject' in res:
                        res['subject'] = {'reference': f'urn:uuid:{patient_id}'}
                    
                    safe_resources.append(res)
            result = safe_resources
        else:
            result = get_single_resource([resources], actual_resource_type)
            result = ensure_id(result)
            
            # Composition profile
            if is_composition:
                result.setdefault('meta', {})['profile'] = [
                    f"https://nrces.in/ndhm/fhir/r4/StructureDefinition/{resource_type}"
                ]
            
            # Patient reference (YOUR ORIGINAL LOGIC)
            patient_id = state['id_registry'].get('patient_id')
            if patient_id and 'subject' in result:
                result['subject'] = {'reference': f'urn:uuid:{patient_id}'}
        
        # ✅ YOUR ORIGINAL ID REGISTRATION LOGIC (handles lists AND singles)
        if isinstance(result, list):
            state['id_registry'][f'{resource_type.lower()}_refs'] = [
                {'reference': f'urn:uuid:{r["id"]}'} for r in result
            ]
        else:
            state['id_registry'][f'{resource_type.lower()}_id'] = result['id']
        
        count = len(result) if isinstance(result, list) else 1
        resource_display = "Composition" if is_composition else resource_type
        print(f"✅ {resource_type}: {count} {resource_display}")
        return {"final_resources": [result] if isinstance(result, list) else [result]}
    
    node.__name__ = f"{resource_type.lower()}_node"
    _node_cache[resource_type] = node
    return node


# ✅ CLEAR CACHE BETWEEN WORKFLOWS (if needed)
def clear_node_cache():
    global _node_cache
    _node_cache = {}

def assembly_node(state):
    """Your logic + Composition FIRST + DocumentReference LAST"""
    bundle = {
        "resourceType": "Bundle",
        "id": str(uuid.uuid4()),
        "meta": {"profile": ["https://nrces.in/ndhm/fhir/r4/StructureDefinition/DocumentBundle"]},
        "type": "document",
        "identifier": {"system": "https://www.abdm.gov.in/bundle", "value": str(uuid.uuid4())},
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "entry": []
    }
    
    clinical_artifact = state.get('clinical_artifact')
    
    # ✅ STEP 1: YOUR ORIGINAL Composition logic (IMPROVED matching)
    composition_found = False
    for resources in state["final_resources"]:
        if isinstance(resources, list):
            for comp in resources:
                if (comp.get('resourceType') == 'Composition' and 
                    clinical_artifact in [p.split('/')[-1] for p in comp.get('meta', {}).get('profile', [])]):
                    bundle["entry"].insert(0, {
                        "fullUrl": f"urn:uuid:{comp['id']}",
                        "resource": comp
                    })
                    composition_found = True
                    print(f"✅ Composition ({clinical_artifact}) added FIRST")
                    break
            if composition_found:
                break
    
    # ✅ STEP 2: YOUR EXACT OTHER RESOURCES LOGIC
    seen_ids = {entry['resource']['id'] for entry in bundle["entry"]}
    doc_refs = []  # Collect DocumentReference separately
    
    # First pass: collect DocumentReference
    for resources in state["final_resources"]:
        if isinstance(resources, list):
            for r in resources:
                if (isinstance(r, dict) and r.get('resourceType') == 'DocumentReference' and 
                    r.get('id') not in seen_ids):
                    doc_refs.append(r)
        elif (isinstance(resources, dict) and resources.get('resourceType') == 'DocumentReference' and 
              resources.get('id') not in seen_ids):
            doc_refs.append(resources)
    
    # Second pass: add NON-DocumentReference (YOUR EXACT LOGIC)
    for resources in state["final_resources"]:
        if isinstance(resources, list):
            for r in resources:
                if (isinstance(r, dict) and r.get('id') not in seen_ids and 
                    r.get('resourceType') != 'DocumentReference'):
                    seen_ids.add(r['id'])
                    bundle["entry"].append({
                        "fullUrl": f"urn:uuid:{r['id']}",
                        "resource": r
                    })
        elif (isinstance(resources, dict) and resources.get('id') not in seen_ids and 
              resources.get('resourceType') != 'DocumentReference'):
            seen_ids.add(resources['id'])
            bundle["entry"].append({
                "fullUrl": f"urn:uuid:{resources['id']}",
                "resource": resources
            })
    
    # ✅ STEP 3: DocumentReference LAST (NEW)
    for doc_ref in doc_refs:
        seen_ids.add(doc_ref['id'])
        bundle["entry"].append({
            "fullUrl": f"urn:uuid:{doc_ref['id']}",
            "resource": doc_ref
        })
    
    print(f"✅ Bundle: {len([e for e in bundle['entry'] if e['resource']['resourceType']=='Composition'])} Composition + "
          f"{len(doc_refs)} DocumentReference LAST + {len(bundle['entry'])} total")
    return {"final_resources": [bundle]}

def build_dynamic_workflow(clinical_artifact: str, selected_other_resources: List[str], rulebook_paths: Dict[str, str]):
    must_resources = get_must_resources(clinical_artifact)
    selected_other_resources = [res for res in selected_other_resources if res not in must_resources]
    all_resources = list(set(must_resources + selected_other_resources))
    all_resources.append(clinical_artifact)
    
    print(f"📋 Workflow for {clinical_artifact}: {all_resources}")
    
    workflow = StateGraph(AgentState)
    
    # ✅ CREATE NODES - Each resource gets EXACTLY ONE node
    created_nodes = set()
    for resource in all_resources:
        node_name = resource.lower()
        if node_name not in created_nodes:
            node_func = create_resource_node(resource)
            workflow.add_node(node_name, node_func)
            created_nodes.add(node_name)
            print(f"✅ Added node: {node_name}")
    
    # Topological sort (unchanged)
    def topological_sort(resources):
        visited = set()
        order = []
        def visit(resource):
            if resource in visited: return
            visited.add(resource)
            for dep in RESOURCE_DEPENDENCIES.get(resource, []):
                if dep in resources:
                    visit(dep)
            order.append(resource)
        for resource in resources:
            visit(resource)
        return order
    
    resource_order = topological_sort(all_resources)
    print(f"📊 Execution order: {[r.lower() for r in resource_order]}")
    
    # Safe edges
    for i in range(len(resource_order) - 1):
        current = resource_order[i].lower()
        next_node = resource_order[i + 1].lower()
        if current in workflow.nodes and next_node in workflow.nodes:
            workflow.add_edge(current, next_node)
            print(f"➡️  Edge: {current} → {next_node}")
    
    # Assembly
    workflow.add_node("assembly", assembly_node)
    last_node = resource_order[-1].lower()
    if last_node in workflow.nodes:
        workflow.add_edge(last_node, "assembly")
    workflow.add_edge("assembly", END)
    
    if "patient" in workflow.nodes:
        workflow.set_entry_point("patient")
    
    return workflow.compile(), all_resources

import json

def sanitize_fhir_resource(resource):
    res_type = resource.get("resourceType")
    if not res_type: return

    # Recurse into nested Bundles
    if res_type == "Bundle":
        for entry in resource.get("entry", []):
            if "resource" in entry:
                sanitize_fhir_resource(entry["resource"])
        return

    # Recurse into contained resources
    if "contained" in resource and isinstance(resource["contained"], list):
        for contained_res in resource["contained"]:
            sanitize_fhir_resource(contained_res)

    # 1. 'entry' is ONLY valid on Bundle
    if res_type != "Bundle" and "entry" in resource:
        del resource["entry"]
        
    # Remove hallucinated fields
    if "entity" in resource: del resource["entity"]
    if "permission" in resource: del resource["permission"]
        
    # 2. 'type' formatting
    if res_type in ["Organization", "InsurancePlan"] and "type" in resource:
        system_url = "http://terminology.hl7.org/CodeSystem/organization-type" if res_type == "Organization" else "http://terminology.hl7.org/CodeSystem/insurance-plan-type"
        if isinstance(resource["type"], str):
            code = "pay" if res_type == "Organization" else "medical"
            resource["type"] = [{"coding": [{"system": system_url, "code": code, "display": resource["type"]}]}]
        elif isinstance(resource["type"], dict):
            resource["type"] = [resource["type"]]
        elif isinstance(resource["type"], list):
            # Fix hallucinated 'insurance' code for Organization
            for t in resource["type"]:
                if "coding" in t and isinstance(t["coding"], list):
                    for c in t["coding"]:
                        if res_type == "Organization" and c.get("code") == "insurance":
                            c["code"] = "pay"
                            c["system"] = system_url
                        elif res_type == "InsurancePlan" and c.get("code") == "medical":
                            c["system"] = system_url
            
    if res_type == "DocumentReference":
        if resource.get("status") not in ["current", "superseded", "entered-in-error"]:
            resource["status"] = "current"
        if "type" in resource:
            if isinstance(resource["type"], list):
                resource["type"] = resource["type"][0] if len(resource["type"]) > 0 else {}
        # docStatus — ReferredDocumentStatus value set
        # Valid codes: preliminary | final | amended | entered-in-error
        if "docStatus" in resource:
            _DOC_STATUS_MAP = {
                "completed": "final",
                "complete":  "final",
                "done":      "final",
                "approved":  "final",
                "draft":     "preliminary",
                "active":    "preliminary",
                "pending":   "preliminary",
                "revised":   "amended",
                "updated":   "amended",
                "cancelled": "entered-in-error",
                "error":     "entered-in-error",
            }
            _VALID_DOC_STATUS = {"preliminary", "final", "amended", "entered-in-error"}
            ds = resource["docStatus"]
            if ds not in _VALID_DOC_STATUS:
                resource["docStatus"] = _DOC_STATUS_MAP.get(ds, "final")

    # 3. 'ownedBy' in InsurancePlan must be a Reference (an object), not an array.
    if res_type == "InsurancePlan" and "ownedBy" in resource:
        if isinstance(resource["ownedBy"], list):
            resource["ownedBy"] = resource["ownedBy"][0] if len(resource["ownedBy"]) > 0 else {}

    # 4. Clean up InsurancePlan hallucinations
    if res_type == "InsurancePlan":
        if "benefit" in resource: del resource["benefit"]
        if "exclusion" in resource: del resource["exclusion"]
        if "note" in resource: del resource["note"]
        for cov in resource.get("coverage", []):
            if "description" in cov: del cov["description"]
            if "type" not in cov:
                cov["type"] = {"coding": [{"system": "http://terminology.hl7.org/CodeSystem/insurance-plan-type", "code": "medical"}]}
            if "benefit" not in cov or not isinstance(cov["benefit"], list) or len(cov["benefit"]) == 0:
                cov["benefit"] = [{"type": {"coding": [{"code": "benefit"}]}}]
            # Fix limit object hallucinations inside benefit
            if isinstance(cov["benefit"], list):
                for ben in cov["benefit"]:
                    if "limit" in ben:
                        # limit must be an array of objects. Just delete to be safe if hallucinated
                        del ben["limit"]
                    if "description" in ben:
                        del ben["description"]
                        
        if "identifier" in resource and isinstance(resource["identifier"], list):
            for ident in resource["identifier"]:
                if ident.get("system") == "uin":
                    ident["system"] = "https://irdai.gov.in/uin"

    # 5. Fix missing required fields using 'display' instead of 'reference' to bypass resolution errors
    if res_type == "Procedure":
        if "status" not in resource: resource["status"] = "completed"
        if "subject" not in resource: resource["subject"] = {"display": "Unknown Patient"}
            
    if res_type == "ImagingStudy":
        if resource.get("status") not in ["registered", "available", "cancelled", "entered-in-error", "unknown"]:
            resource["status"] = "available"
            
    if res_type == "Coverage":
        if "status" not in resource: resource["status"] = "active"
        if "beneficiary" not in resource: resource["beneficiary"] = {"display": "Unknown Patient"}
        if "payor" not in resource: resource["payor"] = [{"display": "Unknown Organization"}]
            
    if res_type in ["Organization", "InsurancePlan"]:
        if "name" not in resource and "identifier" not in resource:
            resource["name"] = "Unknown " + res_type
            
    # 6. Composition fields
    if res_type == "Composition":
        if "author" not in resource or resource["author"] is None:
            resource["author"] = [{"display": "Unknown Author"}]
        elif not isinstance(resource["author"], list):
            resource["author"] = [resource["author"]]
            
        for sec in resource.get("section", []):
            if "status" in sec: del sec["status"]
            if "text" in sec and isinstance(sec["text"], str):
                sec["text"] = {"status": "generated", "div": f"<div xmlns=\"http://www.w3.org/1999/xhtml\">{sec['text']}</div>"}
            elif "text" not in sec and "entry" not in sec:
                sec["text"] = {"status": "generated", "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">No content</div>"}

    # 7. Practitioner qualification
    if res_type == "Practitioner":
        for qual in resource.get("qualification", []):
            if "text" in qual:
                if "code" not in qual: qual["code"] = {"text": qual["text"]}
                del qual["text"]
            if "code" not in qual: qual["code"] = {"text": "Unknown Qualification"}
            
    # 8. Encounter fields
    if res_type == "Encounter":
        if "serviceType" in resource and isinstance(resource["serviceType"], list):
            resource["serviceType"] = resource["serviceType"][0] if resource["serviceType"] else {}
        for loc in resource.get("location", []):
            if "display" in loc:
                loc["location"] = {"display": loc["display"]}
                del loc["display"]
        if "period" in resource and "start" in resource["period"]:
            if "T" in resource["period"]["start"] and "Z" not in resource["period"]["start"] and "+" not in resource["period"]["start"]:
                resource["period"]["start"] += "Z"
                
    # 9. ImagingStudy fields
    if res_type == "ImagingStudy":
        for series in resource.get("series", []):
            if "role" in series: del series["role"]
            if "modality" not in series: series["modality"] = {"system": "http://dicom.nema.org/resources/ontology/DCM", "code": "UNKNOWN"}
        if "started" in resource and "T" in resource["started"] and "Z" not in resource["started"] and "+" not in resource["started"]:
            resource["started"] += "Z"
            
    if res_type == "Appointment":
        valid_statuses = ["proposed", "pending", "booked", "arrived", "fulfilled", "cancelled", "noshow", "entered-in-error", "checked-in", "waitlist"]
        if resource.get("status") not in valid_statuses:
            resource["status"] = "fulfilled" if resource.get("status") in ["completed", "finished", "done"] else "booked"

    # 10. DiagnosticReport & Observation Date fields
    if res_type == "DiagnosticReport":
        if "issued" in resource and "T" in resource["issued"] and "Z" not in resource["issued"] and "+" not in resource["issued"]:
            resource["issued"] += "Z"
        if "effectiveDateTime" in resource and "T" in resource["effectiveDateTime"] and "Z" not in resource["effectiveDateTime"] and "+" not in resource["effectiveDateTime"]:
            resource["effectiveDateTime"] += "Z"
        if "result" in resource:
            resource["result"] = [r for r in resource["result"] if not r.get("reference", "").startswith("Practitioner/")]
            
    if res_type == "Observation":
        if "procedure" in resource: del resource["procedure"]
        if "effectiveDateTime" in resource and "T" in resource["effectiveDateTime"] and "Z" not in resource["effectiveDateTime"] and "+" not in resource["effectiveDateTime"]:
            resource["effectiveDateTime"] += "Z"
            
    # 11. Condition category codes
    if res_type == "Condition" and "category" in resource and isinstance(resource["category"], list):
        for cat in resource["category"]:
            if "coding" in cat and isinstance(cat["coding"], list):
                for coding in cat["coding"]:
                    if coding.get("system") == "http://terminology.hl7.org/CodeSystem/condition-category" and coding.get("code") == "encounter-related":
                        coding["code"] = "encounter-diagnosis"

    # 12. ClaimResponse.outcome — RemittanceOutcome value set
    #     Valid codes: queued | complete | error | partial
    #     LLMs commonly hallucinate: pending, approved, denied, partially-approved
    if res_type == "ClaimResponse" and "outcome" in resource:
        _OUTCOME_MAP = {
            "pending":            "queued",
            "in-progress":        "queued",
            "processing":         "queued",
            "approved":           "complete",
            "accepted":           "complete",
            "paid":               "complete",
            "denied":             "error",
            "rejected":           "error",
            "partially-approved": "partial",
            "partial-approval":   "partial",
        }
        _VALID_OUTCOMES = {"queued", "complete", "error", "partial"}
        outcome = resource["outcome"]
        if outcome not in _VALID_OUTCOMES:
            resource["outcome"] = _OUTCOME_MAP.get(outcome, "queued")

    # 13. Claim.use — valid: claim | preauthorization | predetermination
    if res_type == "Claim" and "use" in resource:
        if resource["use"] not in {"claim", "preauthorization", "predetermination"}:
            resource["use"] = "claim"

    # 14. Claim/ClaimResponse.status — valid: active | cancelled | draft | entered-in-error
    if res_type in {"Claim", "ClaimResponse"} and "status" in resource:
        if resource["status"] not in {"active", "cancelled", "draft", "entered-in-error"}:
            resource["status"] = "active"


def clean_and_reorder_bundle(bundle):
    entries = bundle.get("entry", [])
    
    # Identify indices for removal and relocation
    composition_entry = None
    cleaned_entries = []

    for entry in entries:
        resource = entry.get("resource", {})
        res_type = resource.get("resourceType")

        # Map ABDM Profile names back to standard FHIR R4 resource types
        if res_type in ["DiagnosticReportRecord", "DischargeSummaryRecord", "WellnessRecord", "HealthDocumentRecord", "PrescriptionRecord", "InsurancePlanBundle"]:
            resource["resourceType"] = "Composition"
            res_type = "Composition"
        elif res_type in ["DiagnosticReportLab", "DiagnosticReportImaging"]:
            resource["resourceType"] = "DiagnosticReport"
            res_type = "DiagnosticReport"
        elif res_type in ["ObservationVitalSigns", "ObservationLifestyle", "ObservationWomenHealth", "ObservationPhysicalActivity", "ObservationGeneralAssessment", "ObservationBodyMeasurement"]:
            resource["resourceType"] = "Observation"
            res_type = "Observation"
            
        # Clean up common LLM hallucinations
        sanitize_fhir_resource(resource)

        # Task A: Find the Composition to move it later
        if res_type == "Composition":
            composition_entry = entry
        
        # Task B: Identify and skip the fake 'DocumentBundle' resource
        elif res_type == "DocumentBundle":
            print(f"🗑️ Removing invalid 'DocumentBundle' resource (ID: {resource.get('id')})")
            continue
            
        else:
            cleaned_entries.append(entry)

    # Task C: Reassemble with Composition at the very beginning
    if composition_entry:
        comp_resource = composition_entry.get("resource", {})
        if "section" not in comp_resource or not comp_resource["section"]:
            comp_resource["section"] = [{"title": "Extracted Data", "text": {"status": "generated", "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Auto-generated section</div>"}}]
        
        # Link all bundle resources to the Composition to prevent HAPI "unreachable" errors
        all_refs = [{"reference": f"urn:uuid:{e['resource']['id']}"} for e in cleaned_entries if "id" in e.get("resource", {})]
        if all_refs:
            comp_resource["section"][0]["entry"] = all_refs
            
        final_entries = [composition_entry] + cleaned_entries
        bundle["entry"] = final_entries
    else:
        bundle["entry"] = cleaned_entries

    return bundle

def document_reference_node(bundle, pdf_base64):

    updated = False

    for entry in bundle.get("entry", []):
        resource = entry.get("resource", {})

        if resource.get("resourceType") == "DocumentReference":

            # If content does NOT exist → create it
            if "content" not in resource or not resource["content"]:

                resource["content"] = [
                    {
                        "attachment": {
                            "contentType": "application/pdf",
                            "data": pdf_base64
                        }
                    }
                ]
                print(resource["content"][0]['attachment']['data'])
                # print("Created new content block")

            else:
                # Content exists → update attachment
                attachment = resource["content"][0].setdefault("attachment", {})

                attachment["contentType"] = "application/pdf"
                attachment["data"] = pdf_base64
                print(attachment['data'])
                # print("Updated existing content block")

    return bundle

def run_abdm_pipeline(extracted_text: str, clinical_artifact: str, selected_other_resources: List[str], output_dir=None, pdf_base64=None, idx=None, model: str = _DEFAULT_MODEL):
    # Complete rulebook paths (add all your paths)
    rulebook_paths = {
        # Your existing paths + add for all resources
        "Patient": "./rulebooks_updated/StructureDefinition-Patient_updated.json",
        "Organization": "./rulebooks_updated/StructureDefinition-Organization_updated.json",
        # ... add all 38 resources
        **{
            res: f"./rulebooks_updated/StructureDefinition-{res}_updated.json"
            for res in abdm_extraction_dictionary["OtherResources"]
        }
    }
    
    initial_state = {
        "text": extracted_text,
        "clinical_artifact": clinical_artifact,
        "id_registry": {},
        "final_resources": [],
        "rulebook_paths": rulebook_paths,
        "model": model,  # propagate model selection through the LangGraph state
    }
    
    # Build and run dynamic workflow
    app, used_resources = build_dynamic_workflow(clinical_artifact, selected_other_resources, rulebook_paths)
    # output_dir is legacy — pipeline uploads directly to GCS.
    # Use a transient temp path only as a fallback label (never written to disk).
    import tempfile
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)
    _out_label = output_dir or tempfile.gettempdir()
    output_path = os.path.join(_out_label, f"FHIR_BUNDLE_{clinical_artifact}_Patient_{idx}.json")



    print(f"🚀 Starting FHIR Bundle Generation for Patient {idx}...")
    final_output = app.invoke(initial_state)
    bundle = final_output['final_resources'][-1]
    
    # Process the bundle in memory
    bundle = clean_and_reorder_bundle(bundle)
    bundle = document_reference_node(bundle, pdf_base64=pdf_base64)
    
    # Upload to GCS instead of local file save
    from utils.gcs_storage import upload_json_to_gcs
    filename = f"FHIR_BUNDLE_{clinical_artifact}_Patient_{idx}.json"
    gcs_uri = upload_json_to_gcs(bundle, "json_output/abdm", filename)
    
    print(f"\n SUCCESS! FHIR Bundle generated (GCS: {gcs_uri})")
    print(f" Resources processed: {used_resources}")
    print(f" Bundle entries: {len(bundle['entry'])}")
    
    return bundle


# ═══════════════════════════════════════════════════════════════════════════════
# NHCX (Insurance) pipeline — needed by pdf2nhcx/tasks.py.
# This file is copied last in the Dockerfile onto /app/utils/llm_requirements.py,
# so it must contain all functions from both services.
# ═══════════════════════════════════════════════════════════════════════════════

def _nhcx_get_must_resources_llm(artifact):
    if artifact == "InsurancePlanBundle":
        return ["InsurancePlanBundle", "InsurancePlan", "Organization", "Condition", "DocumentReference"]
    return []


def create_insurance_node(resource_type: str):
    """Factory for NHCX insurance resource nodes (mirrors ABDM's create_resource_node)."""
    if resource_type in _node_cache:
        return _node_cache[resource_type]

    def node(state: AgentState):
        model = state.get('model', _DEFAULT_MODEL)
        is_insurance_bundle = resource_type == "InsurancePlanBundle"
        actual_resource_type = "Bundle" if is_insurance_bundle else resource_type

        resources = run_extraction_agent(state, actual_resource_type, model)
        resources = normalize_resource_output(resources, actual_resource_type)

        if isinstance(resources, list):
            safe_resources = []
            max_items = 1 if is_insurance_bundle else 15
            for res in resources[:max_items]:
                if isinstance(res, dict):
                    if res.get("resourceType") != actual_resource_type:
                        res["resourceType"] = actual_resource_type
                    if is_insurance_bundle:
                        res.setdefault('meta', {})['profile'] = [
                            "https://nrces.in/ndhm/fhir/r4/StructureDefinition/InsurancePlanBundle"
                        ]
                        res['type'] = 'collection'
                    res = ensure_id(res)
                    payer_id = state['id_registry'].get('organization_id')
                    if payer_id and resource_type == "InsurancePlan":
                        res['ownedBy'] = {'reference': f'urn:uuid:{payer_id}'}
                    safe_resources.append(res)
            result = safe_resources
        else:
            result = get_single_resource([resources], actual_resource_type)
            result = ensure_id(result)
            if is_insurance_bundle:
                result.setdefault('meta', {})['profile'] = [
                    "https://nrces.in/ndhm/fhir/r4/StructureDefinition/InsurancePlanBundle"
                ]
                result['type'] = 'collection'
            payer_id = state['id_registry'].get('organization_id')
            if payer_id and resource_type == "InsurancePlan":
                result['ownedBy'] = {'reference': f'urn:uuid:{payer_id}'}

        if isinstance(result, list):
            state['id_registry'][f'{resource_type.lower()}_refs'] = [
                {'reference': f'urn:uuid:{r["id"]}'} for r in result
            ]
            if resource_type == "Organization" and len(result) > 0:
                state['id_registry']['organization_id'] = result[0]['id']
        else:
            state['id_registry'][f'{resource_type.lower()}_id'] = result['id']
            if resource_type == "Organization":
                state['id_registry']['organization_id'] = result['id']

        return {"final_resources": [result] if isinstance(result, list) else [result]}

    node.__name__ = f"{resource_type.lower()}_node"
    _node_cache[resource_type] = node
    return node


def insurance_assembly_node(state):
    """Assemble the final NHCX InsurancePlanBundle with InsurancePlan first."""
    from datetime import datetime, timezone
    bundle = {
        "resourceType": "Bundle",
        "id": str(uuid.uuid4()),
        "meta": {"profile": ["https://nrces.in/ndhm/fhir/r4/StructureDefinition/InsurancePlanBundle"]},
        "type": "collection",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "entry": []
    }
    plan_found = False
    seen_ids = set()
    for resources_list in state["final_resources"]:
        if isinstance(resources_list, list):
            for res in resources_list:
                if isinstance(res, dict) and res.get('resourceType') == 'InsurancePlan':
                    bundle["entry"].insert(0, {"fullUrl": f"urn:uuid:{res['id']}", "resource": res})
                    seen_ids.add(res['id'])
                    plan_found = True
                    break
        if plan_found:
            break

    supporting_entries = []
    attachment_entries = []
    for resources_list in state["final_resources"]:
        if not isinstance(resources_list, list):
            resources_list = [resources_list]
        for r in resources_list:
            if not isinstance(r, dict) or r.get('id') in seen_ids:
                continue
            entry = {"fullUrl": f"urn:uuid:{r['id']}", "resource": r}
            if r.get('resourceType') in ['DocumentReference', 'Binary']:
                attachment_entries.append(entry)
            else:
                supporting_entries.append(entry)
            seen_ids.add(r['id'])

    bundle["entry"].extend(supporting_entries)
    bundle["entry"].extend(attachment_entries)
    print(f"NHCX Bundle: {len(bundle['entry'])} resources")
    return {"final_resources": [bundle]}


def build_insurance_workflow(clinical_artifact: str, selected_other_resources: List[str], rulebook_paths: Dict[str, str]):
    """Build a LangGraph workflow for NHCX insurance bundle generation."""
    must_resources = _nhcx_get_must_resources_llm(clinical_artifact)
    selected_other_resources = [r for r in selected_other_resources if r not in must_resources]
    all_resources = list(set(must_resources + selected_other_resources))
    if clinical_artifact not in all_resources:
        all_resources.append(clinical_artifact)

    workflow = StateGraph(AgentState)
    created_nodes = set()
    for resource in all_resources:
        node_name = resource.lower()
        if node_name not in created_nodes:
            workflow.add_node(node_name, create_insurance_node(resource))
            created_nodes.add(node_name)

    def topological_sort(resources):
        visited = set()
        order = []
        def visit(r):
            if r in visited: return
            visited.add(r)
            for dep in RESOURCE_DEPENDENCIES.get(r, []):
                if dep in resources:
                    visit(dep)
            order.append(r)
        for r in resources:
            visit(r)
        return order

    resource_order = topological_sort(all_resources)
    for i in range(len(resource_order) - 1):
        workflow.add_edge(resource_order[i].lower(), resource_order[i + 1].lower())

    workflow.add_node("assembly", insurance_assembly_node)
    workflow.add_edge(resource_order[-1].lower(), "assembly")
    workflow.add_edge("assembly", END)

    if "organization" in created_nodes:
        workflow.set_entry_point("organization")
    else:
        workflow.set_entry_point(resource_order[0].lower())

    return workflow.compile(), all_resources


def run_nhcx_insurance_pipeline(distilled_text: str, clinical_artifact: str, selected_other_resources: List[str], output_dir=None, pdf_base64=None, idx=None, model: str = _DEFAULT_MODEL):
    """Run the full NHCX insurance FHIR bundle generation pipeline."""
    rulebook_paths = {
        "Organization": "./rulebooks_updated/StructureDefinition-Organization_updated.json",
        "InsurancePlan": "./rulebooks_updated/StructureDefinition-InsurancePlan_updated.json",
        "InsurancePlanBundle": "./rulebooks_updated/StructureDefinition-InsurancePlanBundle_updated.json",
        **{res: f"./rulebooks_updated/StructureDefinition-{res}_updated.json" for res in selected_other_resources}
    }

    initial_state = {
        "text": distilled_text,
        "clinical_artifact": clinical_artifact,
        "id_registry": {},
        "final_resources": [],
        "rulebook_paths": rulebook_paths,
        "model": model,
    }

    app, used_resources = build_insurance_workflow(clinical_artifact, selected_other_resources, rulebook_paths)
    print(f"Starting NHCX FHIR Bundle for patient {idx}...")
    final_output = app.invoke(initial_state)
    bundle = final_output['final_resources'][-1]

    bundle = clean_and_reorder_bundle(bundle)
    bundle = document_reference_node(bundle, pdf_base64=pdf_base64)

    from utils.gcs_storage import upload_json_to_gcs
    filename = f"FHIR_BUNDLE_{clinical_artifact}_Patient_{idx}.json"
    gcs_uri = upload_json_to_gcs(bundle, "json_output/nhcx", filename)

    print(f"NHCX FHIR Bundle generated (GCS: {gcs_uri}), entries: {len(bundle.get('entry', []))}")
    return bundle
